version: '3.8'
services:
#    admin:
#        build:
#            context: .
#            dockerfile: Dockerfile
#        volumes:
#            - .:/app
#        ports:
#            - 8002:8000
#        extra_hosts:
#            host.docker.internal: host-gateway
#        depends_on:
#            - admin_db
    admin_db:
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33062:3306
#networks:
#    admin_net:
#       name: microservices_net
